# Generated by Django 4.1.5 on 2023-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('estudio', models.CharField(max_length=40)),
                ('año', models.DateField()),
                ('capitulos', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('año', models.DateField()),
                ('numeros', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=40)),
                ('año', models.DateField()),
                ('vistas', models.IntegerField(default=0)),
                ('imdb', models.FloatField(default=0)),
            ],
        ),
    ]
